# Repositorio destino del package Arduino JWPLC
PLATFORM_REPO=JW-Control/platform-jwplc

# Rama base hacia donde irá el PR
PLATFORM_BASE_BRANCH=main

# Rama generada/actualizada por el workflow
PLATFORM_SYNC_BRANCH=sync/jw-libraries-2.1.0

# Carpeta destino dentro de platform-jwplc
PLATFORM_LIBRARIES_PATH=JWPLC/2.1.0/libraries

# Librerías que se copiarán desde JW-Libraries/libraries/
LIBRARIES="JW_MatrixButtons JW_FRAM JW_RTC JW_SD"